### PR TITLE
JavaScript to TypeScript conversion

### PR DESCRIPTION
**Pull request by prabh1234assla**
## Related Issue
This PR adds type checking and TypeScript advantages to a plain VanillaJs code.

## Description
**_Typescript and Types packages for specific dependencies all added as dev dependencies_**

    - tsconfig.json instantiated using npx tsc --init command
    - required types for different dependencies may have been added using --legacy-peer-flag so watch for that

 
**_Server module set up successfully with TypeScript_**

    - Linting errors showing in IDE{vscode in my case} were dealt using typescript-eslint/eslint-plugin and typescript-eslint/parser
    - Eslint was added as typescript-eslint devdependency and eslint.config.mjs was created in the root folder
    - Server module was reconfigured to now use ts-node to run index.ts
    - Types module created in Server module holds types to be used by Messages and Users modules
    - .env was created and .gitignore was updated to include .env
    - types were added for dependencies as dev dependencies
    - tsconfig.json made in root folder is being extended in server module instead of recreating new ts configuration file
    
    
**_Client module code migrated to Ts_**

    - created types for ChatPage and UserAuthContext
    - for importing svgs created custom type in custom.d.ts
    - commented out DarkModeToggle in index as wasn't being utilized anywhere
    - ChatPage needed GenerateMessageInit and GenerateLocationMessageInit types so were imported from server module
    - had to change the way setRoomdetail was being imported in the HomePage
    - LocationTemplate and MessageTemplate both extend the GenerateMessageInit and GenerateLocationMessageInit types from server module
    - MicroPhone was using class instead of className and had to configure that also
    - MobileMenu extends RoomUserInit type
    - PrivateRoute needed to change the roomDetail implemetation also inorder to match the TS standards
    - RoomContext type is being used in UserAuthContext.tsx
    - had to install @types/dom-speech-recognition to support _SpeechRecognition class
    - overflowAnchor css styling property was set to bottom which is wrong so changed to revert in div referred by messagesContainerRef
    - USERS type was added in ChatPage
    - handleTyping function in ChatPage was modified as typingTimeout NodeJs.Timeout ref was giving weird errors in Ts
    - handleSubmit function in ChatPage was modified to derive message as (e.currentTarget.elements.namedItem("message") as HTMLInputElement).value for same reasons as typingTimeout ref
    
    
**_ChatPage.tsx modified to reduce error generated on running npm run dev_**

    - SOCKET.ON("message") and SOCKET.ON("locationMessage") updated
    - setUsers not taking users parameter than array of users
    - message = e.target.elements.message.value rewritten
    - typingTimeOut.current  = setTimeout(()... rewritten

**_MessageInit type being utilized in SRC component now_**
    
    - removed GenerateMessageInit as type dependency in the src module
    - DarkModeInit type created in ChatPage.d.ts and NodeJs.TimeOut reference code and handleSubmit code made error free
    - const message = (((e.target as HTMLFormElement).elements as HTMLFormControlsCollection).namedItem("message") as HTMLInputElement).value; is new definition to satisfy TS
    - typingTimeOut is NodeJs.Timeout reference
    - setDarkMode instantiated in MessageTemplate and LocationTemplate Functional Components also ---Definitions neither given Nor I made by myself
    
**_Note.md added stating how to use .env variables for server module_**

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
**from:**
image
image

**to:**
image
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Unused modules have been removed from imports and I have not written modules/files/functions that weren't written in the given codebase. All files are as it is Just with added type annotations. Some codes had error so for removing them I did made changes without affecting the overall code output.

### CODE REVIEW

**Comment by prabh1234assla** [comment]
I tried to deploy it from my local React app and it is working fantabulous. Check the link by yourself. [[react-chat-gssoc.vercel.app](https://react-chat-gssoc.vercel.app/)](url)

**Comment by prabh1234assla** [comment]
Why you closed the PR. I just had one error. Make me understand how to resolve that. It was such a huge task that I handled. Closing it will be such a huge loss to my efforts. Please guide me why you closed the PR.

**Comment by prabh1234assla** [comment]
I try to debug the error and know what kind of issue it was. So, here is the screenshot of what the error link on the error message goes to. 
image

**Comment by urstrulynishkarsh** [comment]
Kindly wait for 2 days actually ui updation is going on so please wait

**Comment by prabh1234assla** [comment]
I have even added the feature request Number

**Pull request closed without merging**
