### PR TITLE
Enhanced chat interface UI

### LINKED ISSUE #182: [Feat]: Enhancing the UI of elements in the chat interface
### Describe the feature

The feature involves enhancing the User Interface (UI) of elements in the chat interface. This would include improving the visual design and making the chat elements more intuitive and user-friendly. Enhancements would cover aspects such as message bubbles, input fields, buttons,  and overall layout adjustments to improve the aesthetic appeal and functionality.

### It should be implemented because

Improved UI enhances the overall user experience, making the chat interface more enjoyable and easier to use. Improved UI can streamline interactions, making it quicker for users to send and receive messages, thus increasing productivity. A visually appealing and intuitive interface can increase user engagement and satisfaction.

### Additional context

Annotation 2024-06-08 111720

### Would you like to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue
Fixes #182 

## Description

- Updated `MessageTemplate` and `ChatPage` component for enhancing the overall user experience.
- Added message container so that the overall look becomes more attractive and streamline interactions.
- Added hovering effects to the bottom buttons.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Video

https://github.com/urstrulynishkarsh/ReactChat/assets/115717746/7876a7c2-803c-4933-a804-5321cc78379b

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@anshulsoni4 please review and merge this PR

Also, add the revelant labels and assign me this PR

Thank you!

**Comment by Asymtode712** [comment]
@anshulsoni4 please review and merge this PR

Also, add the revelant labels and assign me this PR

Thank you!

**Comment by anshulsoni4** [comment]
LGMT

**Comment by urstrulynishkarsh** [comment]
@anshulsoni4  i think there are some mistakes in  this code 
at least you have you run in local host

**Comment by anshulsoni4** [comment]
> @anshulsoni4 i think there are some mistakes in this code at least you have you run in local host

looks fine to me

**Pull request merged**
