### PR TITLE
fixes #111 Logo implementation.

### LINKED ISSUE #111: Logo creation for the website
### Describe the feature

I want to create a unique logo for the website.

Please assign this issue to me under GSSoC'24.
I hope I will not disappoint you and would like to work on this issue.

### It should be implemented because

It gived unique identity to the website. And people can remember the website with the help of the logo in case they want to visit again.

### Additional context

_No response_

### Would you like to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by jain-anshika**
issue: #111 
I added the logo in the assets folder.

image

I hope you liked the logo.

### CODE REVIEW

**Review by asr2003 — APPROVED** [review]
@jain-anshika logo looks visually appealing. Great work!

**Comment by asr2003** [comment]
@urstrulynishkarsh What are your thoughts?

**Comment by asr2003** [comment]
@jain-anshika Can you also add this logo to pages in the website by opening another issue?

**Comment by jain-anshika** [comment]
@urstrulynishkarsh @asr2003 I would be glad to work on another issue. 
I will open one more issue for adding logo to website pages. 
Thanks!

**Pull request merged**
