### PR TITLE
The home page is redesigned and made more appealing

### PR DESCRIPTION
**Pull request by uraj1**
All the elements of home page are redesigned and the styling is readjusted for the same.
Please verify this and merge the PR

### CODE REVIEW

**Comment by urstrulynishkarsh** [comment]
@uraj1  please make mobile responsive also please fast

**Comment by uraj1** [comment]
I have made it mobile responsive, please check it and merge the PR

**Comment by urstrulynishkarsh** [comment]
@uraj1  its not working properly kindly check all screen

**Comment by uraj1** [comment]
I have made the changes, please merge it to the main branch

**Comment by anshulsoni4** [comment]
pls provide screenshots @uraj1

**Pull request closed without merging**
