### PR TITLE
fix : Only number is allowed in Room No

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
Fixes Issue #99
The room no number input will now allow only numbers .
Before :

Screenshot 2024-05-17 224055

After 

https://github.com/urstrulynishkarsh/ReactChat/assets/118350936/90aac4d3-01dc-4058-aeda-fd15705bcb77

### CODE REVIEW

**Comment by urstrulynishkarsh** [comment]
not working properly

**Comment by Ayushmaanagarwal1211** [comment]
Ok can you please tell me the error you are facing

**Comment by urstrulynishkarsh** [comment]
i am unable to enter display name

**Comment by Ayushmaanagarwal1211** [comment]
Oh i found that actually i didn't see same function is calling by name and room no field i am fixing it

**Pull request closed without merging**
