### PR TITLE
Containerised 

### PR DESCRIPTION
**Pull request by MishraTanishq619**
Fixed : #59 

Done : Create Dockerfiles
Done : Implement Docker Compose

Also : added ".env.example" file 

Done : Update ReadMe accordingly

Screenshots with docker compose command :
Screenshot from 2024-05-15 12-18-44
Screenshot from 2024-05-15 12-14-00

Please accept my PR for GSSOC 2024.

### CODE REVIEW

**Comment by asr2003** [comment]
@MishraTanishq619 Provide a video of running docker instance and accessing it

**Comment by MishraTanishq619** [comment]
[Uploading Screencast from 16-05-24 08:40:49 AM IST.webm…]()

**Comment by urstrulynishkarsh** [comment]
@MishraTanishq619  i need to talk in meeting please arrange one google meet kindly share me link

**Comment by MishraTanishq619** [comment]
Approach me on LinkedIn : https://www.linkedin.com/in/tanishq-mishra-495541255/

We should decide some suitable time.

**Comment by anshulsoni4** [comment]
@MishraTanishq619 any updates on this ?

**Pull request closed without merging**
