### PR TITLE
feat:  Add speech to text feature

### LINKED ISSUE #65: Add speech to text  feature
### Describe the feature

User can also use voice to send the message.

- User click on the mic icon
- Start speak
- Send text message

@urstrulynishkarsh Can you assign this task to me  under GSSOC'24

### It should be implemented because

- It will allow user to chat through voice.
- It will make easy for user.

### Additional context

chat-app

### Would you like to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by gyanendra-baghel**
## What does this PR do?

This PR add  the feature of speech to text

Fixes  #65 

## Screenshot
Screenshot 2024-05-13 233620

## Type of change
- New feature (non-breaking change which add functionalities)

## How should be tested.
1. Join the room
2. Show in the side of input box

### CODE REVIEW

**Comment by urstrulynishkarsh** [comment]
thank you for this wonderful upgradation

**Comment by urstrulynishkarsh** [comment]
@gyanendra-baghel  do one thing more when ever we click on mic button then user know that mic is working do something good for ui

**Comment by gyanendra-baghel** [comment]
Sir, I have to create new issue or create PR through current issue.

**Comment by urstrulynishkarsh** [comment]
I think you can work on this if not work then generate new request

**Pull request merged**
