### PR TITLE
Improve the Room

### PR DESCRIPTION
**Pull request by ankitgupta143**
Update the room by adding some condition to Login into chat app to talk securely

### CODE REVIEW

**Comment by ankitgupta143** [comment]
@urstrulynishkarsh Issue number of PR is 53

**Comment by ankitgupta143** [comment]
@urstrulynishkarsh Sir I Issue the PR request #53

**Comment by urstrulynishkarsh** [comment]
I will add don’t worry about it

**Comment by ankitgupta143** [comment]
@urstrulynishkarsh Ok sir

**Comment by ankitgupta143** [comment]
@urstrulynishkarsh I raised the PR, please check it sir

**Comment by ankitgupta143** [comment]
@asr2003 @urstrulynishkarsh Issue The PR

**Comment by asr2003** [comment]
Still there are merge conflicts src/Components/HomePage.jsx

**Comment by ankitgupta143** [comment]
@urstrulynishkarsh all merge conflict resolve, kindly check and merge the PR #53

**Comment by ankitgupta143** [comment]
@asr2003 @urstrulynishkarsh merge the PR after reviewing it #53

**Pull request closed without merging**
