### PR TITLE
Enhance Chatbox UI Styling and Text Overflow Handling

### PR DESCRIPTION
**Pull request by unnihc369**
This pull request aims to improve the user interface (UI) of the chatbox by implementing several styling enhancements and addressing text overflow issues. The following changes have been made:

Styling Improvements: CSS adjustments have been made to enhance the appearance of the chatbox, including modifications to colors, fonts, spacing, and other visual elements. These changes are intended to make the chatbox more visually appealing and user-friendly.

Text Overflow Handling: CSS modifications have been implemented to address text overflow issues. Now, if the length of a sentence exceeds the size of the chatbox, it gracefully wraps to the next line, ensuring that the content remains readable and does not get cut off.

Screenshots:
Before:
Screenshot 2024-05-13 170316

After:
Screenshot 2024-05-13 170505

### CODE REVIEW

**Comment by asr2003** [comment]
@unnihc369  Resolve the conflicts and LGTM after resolving it

**Review by asr2003 — APPROVED** [review]

**Comment by asr2003** [comment]
@unnihc369 Are there still PRs to submit ? I think you asked to submit multiple PRs for that issue. You can follow up same

**Review by asr2003 — CHANGES_REQUESTED** [review]
Before merging , I think the color consistency is missing. Please make it consistent of messages bg color and sidebar

**Comment by unnihc369** [comment]
Hi @asr2003 ,
I have added a new feature ,this pr is not related to my previous issue. User can see their messages on the right and other's in left. I have improved the ui , please provide me a color so that i can update. It has taken a lot of time to bring this funtionality please consider my pr.

Screenshot:
Screenshot 2024-05-14 000002
Screenshot 2024-05-14 001550

**Comment by asr2003** [comment]
@urstrulynishkarsh It seems like the colors are inconsistent. PTAL and provide suggestions for it

**Comment by Tejsvapandey1** [comment]
@unnihc369  please assign me this issue

**Comment by anshulsoni4** [comment]
there are conflicts in this file @unnihc369

**Comment by anshulsoni4** [comment]
@unnihc369 any updates ?

**Pull request closed without merging**
