### PR TITLE
Adding Google Maps embedding in location message

### PR DESCRIPTION
**Pull request by Sudip200**
## Related Issue
None

## Description
I have added an embedded Google map card like WhatsApp that  can be open or extended

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Sudip200** [comment]
@urstrulynishkarsh kindly review it

**Comment by urstrulynishkarsh** [comment]
well done

**Comment by Sudip200** [comment]
@urstrulynishkarsh kindly assign me to it and add the gssoc tag and level otherwise it will not get counted on gssoc

**Comment by GSS0C24** [comment]
@urstrulynishkarsh Why the labels not assigned. if you have missed please add the same .

**Pull request merged**
