### PR TITLE
Added  background image according to website -   [ #57 ]

### PR DESCRIPTION
**Pull request by dhruv389**
I have changed background for chatroom 

 fixed issue no : #57 

Now this looks like this.
---
Screenshot 2024-05-15 100949

### CODE REVIEW

**Comment by urstrulynishkarsh** [comment]
The background image always same or change random

**Comment by dhruv389** [comment]
The background image always same.

**Review by dhruv389 — COMMENTED** [review]
I change background image to random images every time.

**Comment by urstrulynishkarsh** [comment]
I will check tomorrow and let you know

**Comment by urstrulynishkarsh** [comment]
@dhruv389   i think there is an issue if i refresh the page then chat disconnected while i am merging your branch so kindly look at this issue in your branch

**Comment by dhruv389** [comment]
@urstrulynishkarsh .

**you mean this , when refresh the page in chatroom ,then it show this alert :**
----

image

**Comment by dhruv389** [comment]
This is happens why , because you already  select this **checkbox** so that why it happens

**Please try Chrome browser  , And This Issue also happens with your website .**


image

**Comment by dhruv389** [comment]
Please first Merge this Pull request.

**Comment by urstrulynishkarsh** [comment]
sorry currently i can't add this

**Comment by urstrulynishkarsh** [comment]
Before this its working fine

**Comment by urstrulynishkarsh** [comment]
Some one change the code  sorry for this

**Pull request closed without merging**
