### PR TITLE
Send messages on right and receive on left side 🌟

### PR DESCRIPTION
**Pull request by anurag-adk**
## Related Issue
This PR addresses issue no. #178 concerning the alignment and visual presentation of chat messages.

## Description
Sent messages will now appear on the right side of the chat window, while received messages will appear on the left side. A speech bubble style is added to provide clearer visual distinctions between sent and received messages. User experience is also enhanced in the dark mode improving readability and overall aesthetics of the app. 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Along with the initial issue of changing message alignment, this PR also addresses additional UI/UX enhancements

### CODE REVIEW

**Comment by nityanandbhushan** [comment]
@anurag-adk  is it mobile responsive also??? and i will review your code by tonight

**Comment by anurag-adk** [comment]
@nityanandbhushan Yes it is!

**Comment by nityanandbhushan** [comment]
Screenshot 2024-06-09 at 3 48 21 PM
    please fix it asap

**Comment by urstrulynishkarsh** [comment]
@anurag-adk  please check the image and work on it properly just make from your perspective

**Comment by anurag-adk** [comment]
Okay!

**Comment by anurag-adk** [comment]
@nityanandbhushan @urstrulynishkarsh Please check the changes. Thanks!

**Comment by urstrulynishkarsh** [comment]
Screenshot 2024-06-09 at 9 02 04 PM



please fix this type of message

**Comment by urstrulynishkarsh** [comment]
@anurag-adk

**Comment by anurag-adk** [comment]
@urstrulynishkarsh Review!

**Comment by urstrulynishkarsh** [comment]
Screenshot 2024-06-10 at 9 08 39 AM


IT IS NOT RESPONSIVE  and fix all thing from your side them commit check all cases from your side for laptop video and mobile view

**Comment by anshulsoni4** [comment]
@anurag-adk perform the tasks so that i can merge

**Comment by anurag-adk** [comment]
@anshulsoni4 Please review! I have made the chat section responsive. You can see in the video I checked the cases from my laptop as well.
https://github.com/urstrulynishkarsh/ReactChat/assets/89135704/08712208-e308-4d41-9cb4-816555d505f5

**Comment by urstrulynishkarsh** [comment]
Every thing is find but when  you send long message the side war is going
to small so please fix that part then i can merge it

**Comment by anurag-adk** [comment]
@anshulsoni4 After making several adjustments, I realized the complexity is higher than initially thought. Could you consider upgrading this to a level 2 task? Thanks!

**Comment by anurag-adk** [comment]
@urstrulynishkarsh Could you please explain... side war?

**Comment by urstrulynishkarsh** [comment]
Sidebar of online user listing

**Comment by anurag-adk** [comment]
Oh I see it now. It totally missed my eye. Thanks for pointing it out. I'll definitely fix it ASAP

**Comment by anurag-adk** [comment]
@urstrulynishkarsh Can you give a final review? (ps. could you consider upgrading this to a level 2 task?)

**Comment by urstrulynishkarsh** [comment]
@anshulsoni4 merge this  branch and give pr to @anurag-adk  thank you for giving your time

**Comment by anshulsoni4** [comment]
Thanks for contributing @anurag-adk

**Pull request merged**
