### PR TITLE
able to send file

### PR DESCRIPTION
**Pull request by Venkatknight2295**
#91  code is complete but you should add your aws cloud storage url

### CODE REVIEW

**Comment by Venkatknight2295** [comment]
@urstrulynishkarsh  Atleast for this please give level 2 it took more time as i recently learned backend please

**Comment by Venkatknight2295** [comment]
i will be making another issue about UI enhancements i am going to talk with him and we both will complete the ui

**Comment by urstrulynishkarsh** [comment]
@Venkatknight2295 bro its not working

**Comment by Venkatknight2295** [comment]
conflict done

**Pull request closed without merging**
