### PR TITLE
HOME PAGE UI CHANGED

### PR DESCRIPTION
**Pull request by Venkatknight2295**
#102

### CODE REVIEW

**Comment by urstrulynishkarsh** [comment]
@Venkatknight2295  please check

**Comment by Venkatknight2295** [comment]
yes yes

**Comment by Venkatknight2295** [comment]
doing it

**Comment by Venkatknight2295** [comment]
@urstrulynishkarsh Done please check and lable this PR

**Comment by urstrulynishkarsh** [comment]
not working generate new  request and work on current code

**Comment by Venkatknight2295** [comment]
bro you are constaltly changing the code thats the reaso every time it is showing merge conflicts

**Comment by Venkatknight2295** [comment]
i have changed the conflicts now check

**Comment by urstrulynishkarsh** [comment]
@Venkatknight2295   connect on discord

**Comment by urstrulynishkarsh** [comment]
fast join discord

**Comment by Venkatknight2295** [comment]
yeah

**Pull request closed without merging**
