### PR TITLE
Feat: Display user name with Avatar.

### PR DESCRIPTION
**Pull request by abhiperfect**
This PR solve issue #118 

Screenshot 2024-05-18 165552

### CODE REVIEW

**Comment by asr2003** [comment]
@abhiperfect Can avatars be enhanced ?

**Comment by asr2003** [comment]
In React we can create directly profiles based on their names:
Here's tutorial for your guidance: https://dev.to/surbhidighe/creating-stylish-initial-based-avatars-in-react-277j

**Comment by abhiperfect** [comment]
I have changed simple avatar to name avatar.

Screenshot 2024-05-21 234135

**Comment by anshulsoni4** [comment]
good work @abhiperfect , closing this PR

**Pull request merged**
