### PR TITLE
responsive changes

### PR DESCRIPTION
**Pull request by Venkatknight2295**
#21

### CODE REVIEW

**Comment by Venkatknight2295** [comment]
image
if any changes required please mention

**Comment by Venkatknight2295** [comment]
if you want any UI changes i can do that too making the ui MODERN

**Comment by urstrulynishkarsh** [comment]
Send me from the mobile ss

**Comment by Venkatknight2295** [comment]
Please lable my PR if there are no further changes

**Comment by Venkatknight2295** [comment]
already sent the ss @urstrulynishkarsh

**Comment by urstrulynishkarsh** [comment]
Please make this type responsive

**Comment by Venkatknight2295** [comment]
i didnt get you

**Comment by Venkatknight2295** [comment]
please eloborate

**Comment by urstrulynishkarsh** [comment]
https://meet.google.com/mfh-uwhi-abb
Connect with me at 11 am

**Comment by Venkatknight2295** [comment]
ok

**Comment by Venkatknight2295** [comment]
i am waiting to join the meet

**Comment by Venkatknight2295** [comment]
allow me into the meeting

**Pull request closed without merging**
